In [3]:
x=int(input())
y=int(input())


5
6


In [4]:
import numpy as np


In [10]:
z=np.random.random((x,y))

In [8]:
z


array([[0.7867103 , 0.67434264, 0.26297718, 0.6968029 , 0.7528172 ,
        0.90782388],
       [0.63887321, 0.47681434, 0.45900764, 0.97626997, 0.50143435,
        0.8482641 ],
       [0.85361352, 0.52795811, 0.20303009, 0.68424304, 0.18786571,
        0.12449052],
       [0.84068064, 0.8747717 , 0.16558462, 0.37809044, 0.1764304 ,
        0.54642819],
       [0.79643317, 0.62936415, 0.28151435, 0.01456675, 0.69751808,
        0.58051388]])

In [12]:
a=np.arange(100,125,1)

In [13]:
a


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124])

In [23]:
for i in a:
    j=i+80
    b=np.arange(i,j,5).reshape(8,2)
    print(b)

[[100 105]
 [110 115]
 [120 125]
 [130 135]
 [140 145]
 [150 155]
 [160 165]
 [170 175]]
[[101 106]
 [111 116]
 [121 126]
 [131 136]
 [141 146]
 [151 156]
 [161 166]
 [171 176]]
[[102 107]
 [112 117]
 [122 127]
 [132 137]
 [142 147]
 [152 157]
 [162 167]
 [172 177]]
[[103 108]
 [113 118]
 [123 128]
 [133 138]
 [143 148]
 [153 158]
 [163 168]
 [173 178]]
[[104 109]
 [114 119]
 [124 129]
 [134 139]
 [144 149]
 [154 159]
 [164 169]
 [174 179]]
[[105 110]
 [115 120]
 [125 130]
 [135 140]
 [145 150]
 [155 160]
 [165 170]
 [175 180]]
[[106 111]
 [116 121]
 [126 131]
 [136 141]
 [146 151]
 [156 161]
 [166 171]
 [176 181]]
[[107 112]
 [117 122]
 [127 132]
 [137 142]
 [147 152]
 [157 162]
 [167 172]
 [177 182]]
[[108 113]
 [118 123]
 [128 133]
 [138 143]
 [148 153]
 [158 163]
 [168 173]
 [178 183]]
[[109 114]
 [119 124]
 [129 134]
 [139 144]
 [149 154]
 [159 164]
 [169 174]
 [179 184]]
[[110 115]
 [120 125]
 [130 135]
 [140 145]
 [150 155]
 [160 165]
 [170 175]
 [180 185]]
[[111 116]
 [121 126]

In [15]:
b


array([124, 129, 134, 139, 144, 149, 154, 159, 164, 169, 174, 179, 184,
       189, 194, 199])

In [17]:
b

array([[124, 129],
       [134, 139],
       [144, 149],
       [154, 159],
       [164, 169],
       [174, 179],
       [184, 189],
       [194, 199]])